export const MESSAGE = {
    ARCHIVO_ADJUNTO_NO_CARGADO: "Archivo adjunto no cargado",
    NADA_AGREGADO: "No hay registros agregados",
    NADA_CONFIGURADO: "No hay nada configurado por aquí",
    NADA_SELECCIONADO: "No hay registro seleccionado",
    NO_REGISTROS: "No se encontraron registros",
    NO_REGISTROS_TRAZABILIDAD: "No se encontraron registros de trazabilidades",
    NO_REGISTROS_PROCEDE_CREAR: "No se encontraron registros, por favor proceda con la creación de cada uno de ellos",
    NO_ENCONTRO_RESPONSABLE: "No se encontró responsable",
    SELECCIONA_OPCION: "Selecciona una opción",
    SELECCIONA_OPCION_TIPO_CONTENIDO_DISCRETO: "Selecciona una opción del tipo de contenido discreto",
    PREGUNTA_NO_RESPONDIDA: "Pregunta sin responder",
    RESPUESTA_A_OTRA_OPCION_NO_ESCRITA: "Respuesta a otra opción no escrita",
    NO_REGISTRO_ROLES: "No se encontraron roles para el usuario",
    NO_TAREAS: "No se encontraron tareas",
    NO_AVANCE_TAREAS: "No se encontraron avances de tareas",
    NO_ESCALAS_SALARIALES: "No se encontraron escalas salariales",
    NO_ESCALAS_SALARIALES_VIGENTES: "No se encontraron escalas salariales vigentes",
    NO_NORMATIVIDAD_ASOCIADA: "No se encontró normatividad asociada",
    NO_VIGENCIA_ASOCIADA: "No se encontró vigencia asociada",
    NO_VARIABLE_ASOCIADA: "No se encontró variable asociada",
    NO_VALORES_VARIABLES_EN_VIGENCIA: "No se encontraron valores para las variables en la vigencia",
    NO_EXPRESION_PARA_VARIABLE: "No se encontró una expresión para la variable",
    NO_CONDICIONES_PARA_REGLA: "No se encontraron condiciones para la regla",
}
